const { config } = require("dotenv");

config({
  path: `.env.${process.env.NODE_ENV === "production" ? "production" : "development"}.local`,
});

const { NODE_ENV, BASE_URI, MONGO_URI, PORT, RESEND_KEY, JWT_SECRET, JWT_REFRESH_SECRET, SESSION_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, FRONTEND_URL, REDIS_HOST, REDIS_PASSWORD, REDIS_PORT, REDIS_USERNAME } =
  process.env;

module.exports = {
  NODE_ENV,
  BASE_URI,
  MONGO_URI,
  PORT,
  RESEND_KEY,
  JWT_SECRET,
  JWT_REFRESH_SECRET,
  SESSION_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  FRONTEND_URL,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  REDIS_USERNAME
};
